name: 'Bundle Verifier'
description: 'Verifies a committed distribution bundle is up-to-date with the current source code'
inputs:
  bundle_command:
    description: "Command to generate your bundle. An npm/yarn script is recommended."
    required: true
  bundle_file:
    description: 'Output directory where your bundle is located.'
    required: true
    default: 'dist'
  working_directory:
    description: 'Working directory to use for relative path to bundle_file, and to run the bundle_command in.'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: play-circle
  color: blue
