name: CI for bundle-verifier
on:
  push:
  pull_request:

env:
  BUNDLE_FILE: "dist/index.js"
  BUNDLE_COMMAND: "npm run bundle"
  WORKDIR: "./bundle-verifier"

jobs:
  verify-self:
    name: Verify Bundle Verifier
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      working-directory: ${{ env.WORKDIR }}
      run: npm ci

    - name: Verify Latest Bundle
      uses: ./bundle-verifier
      with:
        bundle_file: ${{ env.BUNDLE_FILE }}
        bundle_command: ${{ env.BUNDLE_COMMAND }}
        working_directory: ${{ env.WORKDIR }}
